### ISSUE TITLE
FriendList implementation

### ISSUE THREAD

**Issue by exmex** [exmex/DCNC#11]
Implement actual friendlist and not just dummy content

# I'm submitting a ...
  - feature request

# What is the current behavior?
A dummy friend gets displayed

# What is the expected behavior?
My friends get displayed

# What is the motivation / use case for changing the behavior?
Part of main gameplay

# Other informations
Screenshot will be uploaded later!

# Log Files
\-

**Comment by exmex** [comment]
I don't know how I should do it. I guess displaying all friends?

**Comment by notByte1337** [comment]
I would find much better when first all the online are displayed & then all the offline. So yes best show all.

**Comment by exmex** [comment]
Fixed with b8bfc76d4ab1a220921bcdc2d1d79d2e5449ffbd
