### ISSUE TITLE
Implement Level Ups

### ISSUE THREAD

**Issue by notByte1337** [exmex/DCNC#13]
English is very bad, lol

Wenn man sich neu Registrieren tut & startet kann man gar nicht aufsteigen... schwer zu erklären daher tue ich ein Screenshot einfach hier unter.

![image](https://user-images.githubusercontent.com/29634796/28944698-ca9df312-78a3-11e7-944e-9e35758312fa.png)

**Comment by Snooxd** [comment]
The same happens to me


![exp](https://user-images.githubusercontent.com/30429297/28957662-45a5c128-78c9-11e7-8734-7b135749f71d.png)

**Comment by exmex** [comment]
If I remember correctly the level up packets aren't even implemented see https://github.com/exmex/DCNC/blob/master/src/GameServer/Network/Handlers/Game.cs#L426 for more information. As you can see I'm just "adding" the EXP from quests to the character. There is no logic yet for level ups.

## German translation
Wenn ich mich recht erinnere sind die Level aufsteigen packete nicht implementiert sieh https://github.com/exmex/DCNC/blob/master/src/GameServer/Network/Handlers/Game.cs#L426 für mehr informationen. Wie du dort sehen kannst füge ich die Erfahrung nur dem Charakter hinzu. Es gibt noch gar keine logik für das Level aufsteigen.

**Comment by notByte1337** [comment]
Okay, would be mega the add or finish as it is in this game is partly about leveln

Bad English, lul

**Comment by exmex** [comment]
The repository contains unfinished code. It doesn't say anywhere that the repository contains a fully working emulator. Of course I'll add more features in the future. But as it stands, this repository contains a WIP emulator.

**Comment by exmex** [comment]
Calculating experience is not that easy :/. The LevelServer.tdf that I've is from 2007? and from DC Alpha. But I found this online:
https://strategywiki.org/wiki/Drift_City/Leveling#Experience_Table
This could be helpful, although some levels are still missing.

**Comment by exmex** [comment]
Closed by 9b6d7fbecf50ae3b655cf5cff5fc2a2162bf9bdf 🎉
