### ISSUE TITLE
Buy Car duplication

### ISSUE THREAD

**Issue by exmex** [exmex/DCNC#18]
# I'm submitting a ...
- bug report

# What is the current behavior?
Buying a car puts a duplicate into the garage

## Steps to reproduce
1. Go in shop
2. Buy a random car
3. Go in garage

# What is the expected behavior?
Have only one car in the garage

# Other information
\-

# Log Files
\-

**Comment by notByte1337** [comment]
![unknown](https://user-images.githubusercontent.com/29634796/29979573-53775468-8f46-11e7-8326-d5bd139c1f0a.png)
Works now.

**Comment by exmex** [comment]
Fixed with ecb1790a55eb6e3633853d88f40c7c82155338db
