### ISSUE TITLE
Car Buy Bug

### ISSUE THREAD

**Issue by notByte1337** [exmex/DCNC#20]
# I'm submitting a ...
  - bug report

# What is the current behavior?
When you buy your third car you get kicked

## Steps to reproduce
1. Buy multiple cars

# Expected behavior
Being able to purchase multiple cars

# Other informations
\-

# Log Files
https://pastebin.com/ancLmkTQ (GameServer)
https://pastebin.com/1q9qBjnj (Client logs)

**Comment by exmex** [comment]
Fixed as of e9fb3a3ac66e1dbe7189368fac92320aa192d3a9
