### ISSUE TITLE
Killing Client

### ISSUE THREAD

**Issue by Bl4ckSkull666** [exmex/DCNC#25]
Hello, 

i get the follow error in GameServer on connect more like 1 people from the same IP to the Server. And both will be Disconnect.

` - Killing off client. Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.:    bei GameServer.Network.Handlers.Joining.PlayerInfoReq(Packet packet)
   bei Shared.Network.DefaultServer.Parse(Packet packet)
   bei Shared.Network.Client.OnData(IAsyncResult result)`

Log File: [GameServer.txt](https://github.com/exmex/DCNC/files/1346221/GameServer.txt)

Sincerely
PapaHarni ;-)

**Comment by exmex** [comment]
Thank you for reporting this issue,
Please modify your issue so it complies with our [issue template](https://github.com/exmex/DCNC/blob/master/ISSUE_TEMPLATE.md)

Also, if possible, please recompile the server in DEBUG mode, and try to reproduce it again.
