### ISSUE TITLE
Players cannot see eachother [MP]

### ISSUE THREAD

**Issue by exmex** [exmex/DCNC#3]
# I'm submitting a ...
  - bug report

# What is the current behavior?
Players cannot see each other driving around

## Steps to reproduce
1. Get 2 Clients into the game
2. Drive to the same position

# What is the expected behavior?
See each other drive around

# Other informations
\-

# Log Files
\-

**Comment by notByte1337** [comment]
Multiplayer Works perfect √

**Comment by exmex** [comment]
Please elaborate what you mean with "works perfect". Useful are:
* Images showing other drivers
* gifs showing other drivers driving around
* Videos showing other drivers driving around
etc.

**Comment by notByte1337** [comment]
"Perfect" was too prematurely.
I've tested it with 3 different computers (at the same time) (Local, hamachi). You cannot see each other but everybody can connect and communicate without any problem
(Translated by exmex)

## German translation

"Perfekt" war von mir ein bisschen Voreilig(sry).
Habe es mit 3 verschieden Computern gleichzeitig getestet (Local, Hamachi). Also man zieht zwar noch den anderen Fahrer nicht aber dennoch lassen sich alle ohne Probleme Verbinden & man kann mit einander Schreiben.

**Comment by exmex** [comment]
With what version did you test? Did you test it with the latest version? 352f27e should've fixed the "not seeing each other" issue

I've edited your comment to include a translation. Since german is not a good language to communicate in since most of the population can speak english, but not german ;)

Oh and thanks for being honest in saying it was prematurely 👍

**Comment by notByte1337** [comment]
Ja, habe es mit der aktuellsten Version getestet.

Ist kein Problem, nur ich kann mindestens 1% Englisch.

**Comment by exmex** [comment]
Oh yes I see. I didn't push that update yet. I'll see If I get around to this today. I'll mark this issue as fixed when I did merge my changes and pushed it. Thanks for bringing this to my attention! About the translation thing: Even a bad translation is a translation ;).

**Comment by notByte1337** [comment]
No Problem.
Will try it in the future.

**Comment by exmex** [comment]
Is this still a thing? Did anyone try yet?

**Comment by exmex** [comment]
c520df8c2f2f2a771b8910a46d8e156d38fc3e2e should have fixed issue regarding multiplayer

**Comment by exmex** [comment]
Still doesn't work according to @Rulake
