### ISSUE TITLE
Mito will not be credited (db)

### ISSUE THREAD

**Issue by notByte1337** [exmex/DCNC#31]
## I'm submitting a ... [REQUIRED]
  - bug report
  
## Server Version (SHA-1 Hash & File version number) [REQUIRED]

Product version: 0.2.1015.47.000000--debug
cfa4501c4f4815c8a046e8be55fe3b0818cebf1e

## What is the current behavior? [REQUIRED]

Mito is not stored in the database after a mission.

## What is the expected behavior? [REQUIRED]

Mito should be included in the database.

## Log Files [REQUIRED]

https://pastebin.com/wfLriSVc(GameServer)

**Comment by exmex** [comment]
It's somehow not even implemented anymore?

https://github.com/exmex/DCNC/blob/a6fb2bd824a92dba55adb853dea957ef22fe5087/src/GameServer/Network/Handlers/Quest/QuestReward.cs#L47
