### ISSUE TITLE
DriftShop purchase bug

### ISSUE THREAD

**Issue by notByte1337** [exmex/DCNC#34]
## I'm submitting a ... [REQUIRED]
  - bug report

## Server Version (SHA-1 Hash & File version number) [REQUIRED]

Server Version 0.2.1016.65.000000--debug
d8a7ec55cde7c5c07556a5619912308418e66004

## What is the current behavior? [REQUIRED]

When you buy an item, the same information is always displayed and you get nothing (screen).

## What is the expected behavior? [REQUIRED]

When you buy something, it is displayed correctly and added to your inventory.

# Other informations

![https://i.imgur.com/ApF1QVx.png](https://i.imgur.com/ApF1QVx.png)

## Log Files [REQUIRED]

\-

**Comment by exmex** [comment]
#19 
DriftShop is not ready and not fully implemented.
